/*
 * Copyright © 2017 Denis Shurygin. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */

package ru.pocketbyte.locolaser.kotlinmpp.utils

/**
 * A set of common template strings for file generation.
 */
object TemplateStr {

    const val GENERATED_CLASS_WARNING =
            "AUTO-GENERATED FILE. DO NOT MODIFY.\n\n" +
            "This class was automatically generated by the LocoLaser tool.\n" +
            "It should not be modified by hand."

    const val GENERATED_CLASS_COMMENT =
            "// AUTO-GENERATED FILE. DO NOT MODIFY.\n" +
            "//\n" +
            "// This class was automatically generated by the LocoLaser tool.\n" +
            "// It should not be modified by hand."
}
