/*
 * Copyright © 2017 Denis Shurygin. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */

package ru.pocketbyte.locolaser.platform.mobile.utils

/**
 * A set of common template strings for file generation.
 */
object TemplateStr {

    const val GENERATED_CLASS_COMMENT =
            "/* AUTO-GENERATED FILE. DO NOT MODIFY.\r\n" +
            " *\r\n" +
            " * This class was automatically generated by the LocoLaser tool.\r\n" +
            " * It should not be modified by hand.\r\n" +
            " */"

    const val GENERATED_KEY_VALUE_PAIR_COMMENT =
            "/* AUTO-GENERATED FILE. DO NOT MODIFY.\r\n" +
            " *\r\n" +
            " * This file was automatically generated by the LocoLaser tool.\r\n" +
            " * It should not be modified by hand.\r\n" +
            " */"

    const val GENERATED_XML_COMMENT =
            "<!-- AUTO-GENERATED FILE. DO NOT MODIFY. -->\r\n" +
            "<!-- This file was automatically generated by the LocoLaser tool. -->\r\n" +
            "<!-- It should not be modified by hand. -->"

    const val XML_DECLARATION = "<?xml version=\"1.0\" encoding=\"utf-8\"?>"

}
