/*
 * Copyright © 2017 Denis Shurygin. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */

package ru.pocketbyte.locolaser.mobile.utils

/**
 * A set of common template strings for file generation.
 */
object TemplateStr {

    val GENERATED_COMMENT_STRINGS = arrayOf(
        "AUTO-GENERATED FILE. DO NOT MODIFY.",
        "This file was automatically generated by the LocoLaser tool.",
        "It should not be modified by hand."
    )

    const val GENERATED_NEW_LINE = "\r\n"

    const val GENERATED_CLASS_COMMENT =
            "/* AUTO-GENERATED FILE. DO NOT MODIFY.\r\n" +
            " *\r\n" +
            " * This class was automatically generated by the LocoLaser tool.\r\n" +
            " * It should not be modified by hand.\r\n" +
            " */"

    const val GENERATED_KEY_VALUE_PAIR_COMMENT =
            "/* AUTO-GENERATED FILE. DO NOT MODIFY.\r\n" +
            " *\r\n" +
            " * This file was automatically generated by the LocoLaser tool.\r\n" +
            " * It should not be modified by hand.\r\n" +
            " */"

    val GENERATED_XML_COMMENT = GENERATED_COMMENT_STRINGS
        .joinToString(GENERATED_NEW_LINE) { "<!-- $it -->" }

    const val XML_DECLARATION = "<?xml version=\"1.0\" encoding=\"utf-8\"?>"

}
